### ISSUE TITLE
cip-0006 duplicated vs temporary dissapearing tx

### ISSUE THREAD

**Issue by CurbShifter** [PoC-Consortium/CIPs#2]
I've seen UTs disappear and reappear in the mempool. 
Some resulting in blocks with 0 tx. how will this work in regards with duplicated UTs described in CIP 0006? As this might cause issues.

**Comment by rico666** [comment]
By "mempool" we refer to the total in-memory storage of all wallets. No single wallet has total awareness of the Burst mempool. Because of CIP1, some wallets may even have set a priori a lower processing capacity for UTs resulting in these wallets dropping UTs sooner than other "bigger" wallets.

This can cause UTs disappearing and reappearing in the mempool "as seen from a single node".

----

As for blocks with 0tx

It is completely in the decision domain of the forging wallet which transactions to add to a block and which not. A forging wallet could decide to forge a 0tx block even if mempool was full. This counter-productive strategy is basically hurting the wallet, because it forfeits all the tx fees it could have added to the block reward itself.

There are other possible scenarios where a 0tx block is forged although there are "somewhere in the mempool" UTs. Namely when the forging wallet has no knowledge of them as they haven't proliferated to it yet as of the time of forging.

While another wallet somewhere can observe UTs - as of time of forging.

----

These topics are related, but not substantial to the gist of CIP6. CIP6 merely shows a way how to protect the mempool from UT spamming attacks where - say - an attacker would flood the network with UTs each 0.00735 Fee well knowing that all cannot be applied and the fees temporarily spent will return to his wallet after the deadline of the UTs is met.

While this cannot de-stabilise the network today by causing out-of-memory problems, it can cause a higher network traffic which is generally undesireable. CIP6 mitigates this attack vector.

**Comment by CurbShifter** [comment]
Thanks for this detailed explanation.
Is the UTs drop selection "random-ish" or based on rules? It doesn't matter in light of original post. But would like to know.

> A forging wallet could decide to forge a 0tx block even if mempool was full. 
Would this be an attack vector in itself? own n% of the network to make it n% slower? (only forging 0 tx blocks).

**Comment by rico666** [comment]
The UT drops happen certainly based on rules, but the ruleset as whole can appear not exactly transparent to a single node as mentioned above. There is one single pseudorandom element in dropping the UTs from UT store and that is by id.

As last resort, when age and fee of an UT resulted in same values. As the Id is part of a hash (pseudorandom) - it's some sort of lottery.

----

A wallet forging 0tx blocks would hurt itself (forfeiting tx fees) so this is what protects us (and e.g. Bitcoin where the same principle applies). Moreover, even a such a wallet with n% of the network would not make the network n% slower. That would only apply if the network was operating at limit capacity.

As currently the network is somewhere 1-3% capacity usage, other blocks could quickly compensate such a "staller".

**Comment by CurbShifter** [comment]
Again thank you. hope you don't mind me continuing this thread; 

>  some wallets may even have set a priori a lower processing capacity for UTs resulting in these wallets dropping UTs sooner than other "bigger" wallets.

Why are UTs being selected to drop from the node while there is low traffic? The mem pool should not have hit the maximum number of unconfirmed transactions, causing it to get candidates to drop. Is there another reason to free up the mempool and drop UTs? Could this be linked to how (often) the 'computational resources available' are defined (CIP1)?

As far as i understand now, i think my main concern is that the current CIP1 implementation is too strong/strict. Causing these unexpected blocks with 0 tx.

**Comment by rico666** [comment]
> Why are UTs being selected to drop from the node while there is low traffic? 

This happens only if the deadline for the transaction has been met. Then this UT is not re-added to the mempool - it's dropped completely.

If you see it "reappearing", it may be another tx that was sent again by the user after the first one failed.

**Comment by CurbShifter** [comment]
> If you see it "reappearing", it may be another tx that was sent again by the user after the first one failed.

Would have to confirm that, but that seems logical.

It's the 0 tx which i was mainly scratching my head over. If UTs only get dropped because of the described reasons, then it can only be because of slow proliferation. thanks.

stickler meeseeks out :cloud: poof!
